Class {
	#name : #MarvinLiteral,
	#superclass : #Object,
	#category : 'Marvin-Compiler-Literals'
}

{ #category : #'as yet unclassified' }
MarvinLiteral >> isBlockLiteral [

	^ false
]

{ #category : #'as yet unclassified' }
MarvinLiteral >> isConstantLiteral [

	^ false
]

{ #category : #'as yet unclassified' }
MarvinLiteral >> isMethodLiteral [

	^ false
]

{ #category : #'as yet unclassified' }
MarvinLiteral >> isObjectLiteral [

	^ false
]
